# Generated by Django 5.1.3 on 2025-03-03 07:43

import carnetizacion.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo_instructor', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('numero_identificacion', models.CharField(max_length=50, unique=True)),
                ('numero_telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modalidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rh',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Rh', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('roll', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDoc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('ficha', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_ficha', models.CharField(max_length=100)),
                ('fecha_inicio', models.CharField(max_length=50)),
                ('instructores', models.ManyToManyField(related_name='fichas', to='carnetizacion.instructor')),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carnetizacion.modalidad')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaEnFormacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carnetizacion.ficha')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carnetizacion.instructor')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas', to='carnetizacion.ficha')),
            ],
        ),
        migrations.AddField(
            model_name='instructor',
            name='rh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carnetizacion.rh'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='roll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carnetizacion.roll'),
        ),
        migrations.CreateModel(
            name='Aprendiz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_documento', models.CharField(max_length=50, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=carnetizacion.models.ruta_foto_aprendiz)),
                ('fecha_descarga', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carnetizacion.estado')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carnetizacion.ficha')),
                ('instructor_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carnetizacion.instructor')),
                ('rh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carnetizacion.rh')),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carnetizacion.roll')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carnetizacion.tipodoc')),
            ],
        ),
    ]
