# Generated by Django 5.1.3 on 2025-02-25 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('ficha', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('nombre_ficha', models.CharField(max_length=255)),
                ('fecha_inicio', models.CharField(max_length=255)),
                ('base', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('correo_instructor', models.EmailField(max_length=254)),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('numero_identificacion', models.CharField(max_length=50)),
                ('clave', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rh',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaEnFormacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas', to='carnetizacion.ficha')),
                ('nombre_ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carnetizacion.ficha')),
                ('nombre_instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carnetizacion.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Aprendiz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(max_length=50)),
                ('numero_identificacion', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('clave', models.CharField(blank=True, max_length=255, null=True)),
                ('ficha', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprendices', to='carnetizacion.ficha')),
                ('instructor_a_cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprendices', to='carnetizacion.instructor')),
                ('rh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprendices', to='carnetizacion.rh')),
            ],
        ),
    ]
