# Generated by Django 5.1.3 on 2025-03-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carnetizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoAprendiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
    ]
